version: '3'
services:
  api:
    container_name: OceanDB_api
    build:
      context: ./app/.
      dockerfile: Dockerfile
    command: uvicorn run app:main --reload
    volumes:
      - ./app/:/app
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env.test
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  db:
    container_name: oceandb_posnet_db
    image: postgres:13
    volumes:
      - pg_oceandb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: oceandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oceandb_1234
    ports:
      - '5432:5432'
 
volumes:
  pg_oceandb_data: